### ISSUE TITLE
I've got following error: Exception unsupported operand type(s) for +=:'float' and 'NoneType'. Any idea to solve this?

### ISSUE THREAD

**Issue by FilipNaudts** [geertmeersman/nexxtmove#69]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Log information**
If possible activate debug logging on the component as mentioned below.

https://www.home-assistant.io/integrations/logger/
```
logger:
  default: warning
  logs:
    custom_components.nexxtmove: debug
```

**Additional context**
